version: '3'

tasks:
  api:
    desc: Build the binary and start the api server.
    deps: [ build ]
    cmds:
      - ./mdclubgo api

  build:
    desc: Build the binary.
    cmds:
      - go build -v
        -ldflags '
        -X "{{.PKG_PATH}}.BuildTime={{.BUILD_TIME}}"
        -X "{{.PKG_PATH}}.BuildCommit={{.BUILD_COMMIT}}"
        '
        -tags '{{.TAGS}}'
        -trimpath -o mdclubgo cmd/main.go
    vars:
      PKG_PATH: github.com/laojianzi/mdclubgo/conf
      BUILD_TIME:
        sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
      BUILD_COMMIT:
        sh: git rev-parse HEAD

  test:
    desc: Run all tests.
    cmds:
      - go test -cover -race -count=1 ./...

  generate-bindata:
    desc: Generate bindata for all assets.
    deps: [ clean ]
    cmds:
      - go generate conf/conf.go
      - go generate internal/email/template/template.go

  clean:
    desc: Cleans up system meta files for code generation.
    cmds:
      - find . -name "*.DS_Store" -type f -delete
